### PR TITLE
WIP: Fix PEP8 violations

### LINKED ISSUE #4: fix PEP8 violations

### PR DESCRIPTION
**Pull request by kevindaum**
This is a work-in-progress. It will close #4. 

I have started by sorting imports, using [django's rules](https://github.com/django/django/blob/master/setup.cfg#L10-L17). Next step is to fix the rest of the pep8 violations. 

I'm not sure whether it makes sense to include tests or docs with this. I could include a link to [django's rules on imports](https://docs.djangoproject.com/en/1.9/internals/contributing/writing-code/coding-style/#imports). Not sure where that would go, though; the README looks more like an intro to callisto than code documentation. Is it intended to stay that way? If so, where should code docs go? 

And tests... I see https://pypi.python.org/pypi/django-test-pep8/0.1 and https://bitbucket.org/pytest-dev/pytest-pep8, but they both look a little old and I'm not sure if they'll fit in with whatever this project is going to use for tests.

### CODE REVIEW

**Comment by kelseyq** [comment]
Thanks Kevin! This looks excellent, and I appreciate the sorted imports change. I'd like to keep the README as a bit of a landing page to describe the projects; while we do need to build out more robust docs beyond that, I'm not totally sure if we need them here--the settings sort of explain themselves, IMO. Can you send over the signed volunteer agreement (https://github.com/SexualHealthInnovations/callisto-core/blob/master/shi-volunteer-agreement.pdf) to tech@sexualhealthinnovations.org? Besides that, the blocker for this (and basically everything in this repo) is #18--I can start working on what will likely be a gnarly merge. My apologies, totally my fault!

**Comment by kelseyq** [comment]
Oh, and I think we can configure Travis to run flake8 to enforce PEP8? I will investigate when I set up #11 (also blocked by #18, sigh)

**Comment by kevindaum** [comment]
Oh, right, I had started reading that volunteer agreement and stopped at this bit:

> You agree not to incorporate into any Sexual Health Innovations property any information or materials owned by you or any third party, or in which you or any third party has an interest, without obtaining Sexual Health Innovations’ prior written consent.

Would that apply to third-party python packages like flake8, isort, etc.?

**Comment by kevindaum** [comment]
Would you like me to wait until you merge https://github.com/SexualHealthInnovations/callisto-core/pull/18 and then start this over? Or do this over based on the `package-callisto-core` branch?

**Comment by kelseyq** [comment]
My apologies, I thought I remembered responding to this! Third-party packages are fine under this agreement. I've merged #18 so let me know how you'd like to proceed with rebasing--I can pitch in too if you'd like since it was such a major change.

**Comment by kevindaum** [comment]
Because this PR affects almost all the files in the project and almost all the files changed when https://github.com/SexualHealthInnovations/callisto-core/pull/18 was merged, I think it'll be way easier to just start over.

**Pull request closed without merging**
