### PR TITLE
allow reports to be sent to multiple recipients

### PR DESCRIPTION
**Pull request by kelseyq**
requested by school client

### CODE REVIEW

**Comment by lynnco** [comment]
Ah, actually, question - 

Do you know if django will migrate the old data with `AlterField `?

**Comment by kelseyq** [comment]
good q -- adding a test to cover

**Comment by lynnco** [comment]
That's a question I've had for a few months actually 😮 not sure how one would cover it with a test

**Comment by kelseyq** [comment]
we use this cool library to test migrations https://github.com/plumdog/django_migration_testcase

**Pull request merged**
