### PR TITLE
update eval for wizard builder changes

### PR DESCRIPTION
**Pull request by lynnco**
depends on https://github.com/SexualHealthInnovations/django-wizard-builder/pull/40

### CODE REVIEW

**Comment by lynnco** [comment]
need to check if this line https://github.com/SexualHealthInnovations/callisto-core/blob/884ba7fe4f52ff184d95ce1763286b9c5692003e/callisto/evaluation/models.py#L96 still works

**Comment by kelseyq** [comment]
do you feel like there's sufficient test coverage of the actual mechanics of evaluation, too? like that questions are extracted accordingly now?

**Comment by lynnco** [comment]
I'm not totally confident that the `FormQuestion`s are properly downcasted (ex: to `Choice` or `RadioButton`), and want to add an explicit test for that

**Comment by lynnco** [comment]
So the concern I had was the `FormQuestion` wouldn't be downcasted to `RadioButton`, which would make this line fail https://github.com/SexualHealthInnovations/callisto-core/blob/884ba7fe4f52ff184d95ce1763286b9c5692003e/callisto/evaluation/models.py#L96

and the eval output wouldn't contain `question.serialize_choices()`

I checked the eval tests and it looks like there's already some `question.serialize_choices()` output from a `RadioButton` in there. That's here https://github.com/SexualHealthInnovations/callisto-core/blob/66112471093594c0c72ca6f22e832427c82a2196/tests/evaluation/tests.py#L196

So the eval tests already cover the radio button not being downcasted. But I added an explicit test for it anyways, because why not https://github.com/SexualHealthInnovations/callisto-core/commit/1ad066d990f3295d51f852a6075077db54760b6a

**Comment by lynnco** [comment]
here's the diff, since github is borked rn

```diff
+    def test_extract_choices(self):
+        self.maxDiff = None
+        self.set_up_simple_report_scenario()
+        anonymised = EvalRow()._extract_answers(json.loads(self.json_report))
+        self.assertIn('radio_choices', anonymised)
```

**Comment by lynnco** [comment]
me and caches are gonna fight https://travis-ci.org/SexualHealthInnovations/callisto-core/jobs/233041032

**Comment by lynnco** [comment]
ok wait, I think wizard builder isn't actually telling callisto-core about it dependencies

**Pull request merged**
