### PR TITLE
Python 2.7 compatibility

### PR DESCRIPTION
**Pull request by divergentdave**
This is for #23. For starters, here's the .travis.yml syntax to skip the Python 3.3/Django 1.9 combination.

### CODE REVIEW

**Comment by divergentdave** [comment]
Okay, the test suite passes now, though I'm wary of other issues lurking on the PDF side.

**Comment by kelseyq** [comment]
Makes sense. Can you add a "Requirements" section to the README indicating that Django 1.8 and 1.9 are supported, and include a note that 2.7 has not been fully manually tested? You can link to #19 which would cover PDF generation there.

**Comment by divergentdave** [comment]
Sure, here you go!

**Comment by kelseyq** [comment]
Looks great, thanks!

**Pull request merged**
