### PR TITLE
Make callisto-core pip installable

### LINKED ISSUE #101: Make callisto-core installable via pip
When I ran `pip install git+https://github.com/SexualHealthInnovations/callisto-core.git@release-7.18.16`, the package appears in my virtualenv site-packages as expected. But the directory tree looked like this:

```
site-packages/
    callisto/
        delivery/
            __init__.py
            ...
        evaluation/
            __init__.py
            ...
```

Specifically, `callisto/__init__.py` was missing. Before adding it, `import callisto` failed. After running `touch path/to/site-packages/callisto/__init__.py`, `import callisto` succeeded.

There are several ways to address this issue, but the goal is to be able to run `pip install callisto-core` then `import callisto` successfully.

### PR DESCRIPTION
**Pull request by jisantuc**
Manually installing dependencies is no fun, fully pip installable
packages are easier to develop with. This change updates metadata in
`setup.py` so that the package can be registered with pip.

Pip deployment:

- Register with pypi and setup your
  [~/.pypirc](https://docs.python.org/2/distutils/packageindex.html#the-pypirc-file)
- `python register.py`
- `python setup.py sdist upload -r pypi`

Future releases will need to update the `download_url` field in
`setup.py`

Fixes #101

### CODE REVIEW

**Comment by jisantuc** [comment]
Upload to `testpypi.python.org` [worked](https://testpypi.python.org/pypi/callisto-core/0.1.0) so I'm assuming live pypi would work just as well -- there's a package index owner field at the bottom that defaults to the uploader, so I didn't want to upload to live pypi from my account

**Comment by kelseyq** [comment]
Hi James!

This looks good to me--thanks so much for this work. I think markdown -> rst would be great--requirements_dev.txt would be a good place for those.

Can you make sure you get your signed volunteer agreement to me so I can accept this patch? Thanks so much!

**Comment by jisantuc** [comment]
[Here's](https://testpypi.python.org/pypi/callisto-core/0.1.0) what it looks like post markdown --> rst

**Comment by kelseyq** [comment]
great! waiting on #116 to merge this and cut our first pip release

**Pull request merged**
