### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by divergentdave**
This addresses #5 by adding a `requirements.txt` file for dependencies, an entry point for running tests, and a basic `.travis.yml` file. Currently Travis CI will run `pyflakes` on everything (I fixed a few unused imports/locals) and run the unit test for the evaluation app. The delivery app tests depend on having `ROOT_URLCONF` set up properly, so I think running them is blocked by #3. As such, `delivery/tests` is skipped for now. Once #4 is done, `pep8` or `flake8` can be added to `.travis.yml`.

You can see builds under my account at https://travis-ci.org/divergentdave/callisto-core

### CODE REVIEW

**Comment by divergentdave** [comment]
Looking forward to the `delivery` app, I added two more commits to switch to PostgreSQL and add another Python library. (SQLite isn't sufficient because it doesn't support distinct() and autoincrement fields have different behavior)

FWIW, I noticed the `account.forms` and `account.tokens` modules are missing. I presume this will be part of #3 as well.

**Comment by kelseyq** [comment]
Wow David, thank you so much! I will be fixing the issues you've found (I didn't quite make the cleanest cut in extracting this from the Django app we run in prod) in the next week and I will review this and merge once those are fixed. This is a great step forward for us!

**Comment by divergentdave** [comment]
You're welcome, happy to help!

**Comment by divergentdave** [comment]
I pushed a bunch of commits to resolve merge commits, fix paths that changed, and move to tox for testing. Tox will now run the tests against both Django 1.8 and Django 1.9. I also enabled Travis CI's caching feature for the .tox directory, which really cuts down run time.

**Pull request merged**
